name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのクローン
      - name: Checkout code
        uses: actions/checkout@v3

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Pythonのバージョンを指定

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r flask/requirements.txt  # Flask用の依存関係をインストール

      # Docker Compose をインストール
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Docker イメージのビルド
      - name: Build Docker Images
        run: docker-compose build

      # コンテナを起動してテストを実行
      - name: Run Tests
        run: |
          docker-compose up -d
          docker exec flask_app pytest  # pytest を使ったテスト実行
          docker-compose down

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # main ブランチのみデプロイ

    steps:
      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_KEY }} user@your-server-ip <<EOF
            cd /path/to/project
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF