name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask/requirements.txt
          pip install pytest

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Images
        run: docker-compose build

      - name: Run Tests
        run: |
          docker-compose up -d
          docker exec flask pytest
          docker-compose down

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_KEY }} user@your-server-ip <<EOF
            cd /path/to/project
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF
